version: '3'
services:
  hugo:
    image: klakegg/hugo:0.82.1-ext-ubuntu-onbuild
    entrypoint: bash
    volumes:
      - ".:/src"
    ports:
        - "1313:1313"
    tty: true
    working_dir: /src